---
title: "RWorksheet_Caoyonan#3b.Rmd"
author: "Leanie G. Caoyonan"
date: "2025-10-13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r data}
#1. Create a data frame using the table below.

#a. Write the codes.
#b. Describe the data. Get the structure or the summary of the data

respondents <- c(1,2,3,4,5,6,7,8,9,10,
                 11,12,13,14,15,16,17,18,19,20)
sex <- c(2,2,1,2,2,2,2,2,2,2,
         1,2,2,2,2,2,2,2,1,2)
fathers_occupation <- c(1,3,3,3,1,2,3,1,1,1,
                        3,2,1,3,3,1,3,1,2,1)
persons_at_home <- c(5,7,3,8,5,9,6,7,8,4,
                     7,5,4,7,8,8,3,11,7,6)
siblings_at_school <- c(6,4,4,1,2,1,5,3,1,2,
                        3,2,5,5,2,1,2,5,3,2)
types_of_houses <- c(1,2,3,1,1,3,3,1,2,3,
                     2,3,2,2,3,3,3,3,3,2)

data <- data.frame(respondents, sex, fathers_occupation, 
                   persons_at_home, siblings_at_school, types_of_houses)
data

#Structure and Summary of the data.
str(data)
summary(data)

#c. Is the mean number of siblings attending is 5?
#No, the mean based on the data is 2.95 as the display shown.
mean_siblings <- mean(data$siblings_at_school)
mean_siblings == 5
mean_siblings

#d. Extract the 1st two rows and then all the columns using the sub-setting functions. Write the codes and its output.
data[1:2, ]

#e. Extract 3rd and 5th row with 2nd and 4th column. Write the codes and its result.
data [c(3, 5), c(2, 4)]

#f. Select the variable types of houses then store the vector that results as types_houses. Write the codes.
types_houses <- data$types_of_houses
types_houses

#g. Select only all Males respondent that their father occupation was farmer. Write the codes and its output.
male_farmer <-subset(data, sex == 1 & fathers_occupation == 1)
male_farmer

#h. Select only all females respondent that have greater than or equal to 5 number of siblings attending school. Write the codes and its outputs.
female_5plus <- subset(data, sex == 2 & siblings_at_school >= 5)
female_5plus
```

```{r data frame}
#2. Write a R program to create an empty data frame. Using the following codes:

df <- data.frame(
  Ints = integer(),
  Doubles = double(),
  Characters = character(),
  Logicals = logical(),
  Factors = factor(),
  stringsAsFactors = FALSE
)

print("Structure of the empty dataframe:")
print(str(df))

#a. Describe the results.
#Describe: The result shows that the empty data frame has 0 rows and 5 columns with different data 
#types. 
#The str() output confirms the structure by showing the column names and their corresponding types 
#even though no data is stored yet. 

```

```{r}

#3. Create a .csv file of this. Save it as HouseholdData.csv
#a. Import the csv file into the R environment. Write the codes.
data <- read.csv("HouseholdData.csv", stringsAsFactors = FALSE)
data

#b. Convert the Sex into factor using factor() function and change it into integer.[Legend: Male = 1 and Female = 2]. Write the R codes and its output.
data$Sex <- factor(data$Sex, levels = c("Male", "Female"))
as.integer(data$Sex)

#c. 
# Correcting column reference
data$Types_of_Houses <- factor(data$Types_of_Houses,
                                levels = c("Wood", "Concrete", "Semi-concrete"))

# Converting the factor to integers
as.integer(data$Types_of_Houses)

#d. 
data$Fathers_Occupation <- factor(data$Fathers_Occupation,
                                  levels = c(1,2,3),
                                  labels = c("Farmer", "Driver", "Others"))
as.integer(data$Fathers_Occupation)

#e. 
subset(data, Sex == "Female" & Fathers_Occupation == "Driver")


# f.
subset(data, siblings_at_school >= 5)


```

```{r}
#4.Interpret the Graph
#The graph shows the sentiments of tweets per day. It shows the dates from July 14 to July 21, 2020
# with the sentiments of Positive, Neutral, and Negative.
#The graph shows the dates with the highest negative score, which are July 15 and July 21
```

